/*
 * Copyright Nathan Jones 2013
 *
 * This file is part of Juzidian.
 *
 * Juzidian is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Juzidian is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Juzidian.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.juzidian.pinyin;

import java.util.Arrays;
import java.util.Collection;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.Parameter;
import org.junit.runners.Parameterized.Parameters;

@RunWith(Parameterized.class)
public class PinyinParserInvalidSyllablesTest {

	@Parameter(0)
	public String text;

	@Parameters(name = "Text ''{0}'' should be invalid pinyin")
	public static Collection<Object[]> parameters() {
		return Arrays.asList(new Object[][] {
				{ "ja" },
				{ "qa" },
				{ "xa" },
				{ "ra" },
				{ "fai" },
				{ "jai" },
				{ "qai" },
				{ "xai" },
				{ "rai" },
				{ "yai" },
				{ "jan" },
				{ "qan" },
				{ "xan" },
				{ "jang" },
				{ "qang" },
				{ "xang" },
				{ "jao" },
				{ "qao" },
				{ "xao" },
				{ "be" },
				{ "pe" },
				{ "fe" },
				{ "je" },
				{ "qe" },
				{ "xe" },
				{ "we" },
				{ "jei" },
				{ "qei" },
				{ "xei" },
				{ "zhei" },
				{ "chei" },
				{ "rei" },
				{ "cei" },
				{ "sei" },
				{ "yei" },
				{ "den" },
				{ "ten" },
				{ "len" },
				{ "jen" },
				{ "qen" },
				{ "xen" },
				{ "yen" },
				{ "eng" },
				{ "jeng" },
				{ "qeng" },
				{ "xeng" },
				{ "yeng" },
				{ "ber" },
				{ "per" },
				{ "mer" },
				{ "fer" },
				{ "der" },
				{ "ter" },
				{ "ner" },
				{ "ler" },
				{ "ger" },
				{ "ker" },
				{ "her" },
				{ "jer" },
				{ "qer" },
				{ "xer" },
				{ "zher" },
				{ "cher" },
				{ "sher" },
				{ "rer" },
				{ "zer" },
				{ "cer" },
				{ "ser" },
				{ "wer" },
				{ "yer" },
				{ "i" },
				{ "fi" },
				{ "gi" },
				{ "ki" },
				{ "hi" },
				{ "wi" },
				{ "ia" },
				{ "fia" },
				{ "gia" },
				{ "kia" },
				{ "hia" },
				{ "wia" },
				{ "ian" },
				{ "fian" },
				{ "gian" },
				{ "kian" },
				{ "hian" },
				{ "wian" },
				{ "iang" },
				{ "fiang" },
				{ "giang" },
				{ "kiang" },
				{ "hiang" },
				{ "wiang" },
				{ "iao" },
				{ "giao" },
				{ "kiao" },
				{ "hiao" },
				{ "wiao" },
				{ "ie" },
				{ "fie" },
				{ "gie" },
				{ "kie" },
				{ "hie" },
				{ "wie" },
				{ "in" },
				{ "fin" },
				{ "din" },
				{ "tin" },
				{ "gin" },
				{ "kin" },
				{ "hin" },
				{ "zhin" },
				{ "chin" },
				{ "shin" },
				{ "rin" },
				{ "zin" },
				{ "cin" },
				{ "sin" },
				{ "win" },
				{ "ing" },
				{ "fing" },
				{ "ging" },
				{ "king" },
				{ "hing" },
				{ "zhing" },
				{ "ching" },
				{ "shing" },
				{ "ring" },
				{ "zing" },
				{ "cing" },
				{ "sing" },
				{ "wing" },
				{ "iong" },
				{ "biong" },
				{ "piong" },
				{ "miong" },
				{ "fiong" },
				{ "diong" },
				{ "tiong" },
				{ "niong" },
				{ "liong" },
				{ "giong" },
				{ "kiong" },
				{ "hiong" },
				{ "zhiong" },
				{ "chiong" },
				{ "shiong" },
				{ "riong" },
				{ "ziong" },
				{ "ciong" },
				{ "siong" },
				{ "wiong" },
				{ "yiong" },
				{ "iu" },
				{ "biu" },
				{ "piu" },
				{ "fiu" },
				{ "tiu" },
				{ "giu" },
				{ "kiu" },
				{ "hiu" },
				{ "zhiu" },
				{ "chiu" },
				{ "shiu" },
				{ "riu" },
				{ "ziu" },
				{ "ciu" },
				{ "siu" },
				{ "wiu" },
				{ "yiu" },
				{ "do" },
				{ "to" },
				{ "no" },
				{ "go" },
				{ "ko" },
				{ "ho" },
				{ "jo" },
				{ "qo" },
				{ "xo" },
				{ "zho" },
				{ "cho" },
				{ "sho" },
				{ "ro" },
				{ "zo" },
				{ "co" },
				{ "so" },
				{ "ong" },
				{ "bong" },
				{ "pong" },
				{ "mong" },
				{ "fong" },
				{ "jong" },
				{ "qong" },
				{ "xong" },
				{ "shong" },
				{ "wong" },
				{ "bou" },
				{ "jou" },
				{ "qou" },
				{ "xou" },
				{ "wou" },
				{ "u" },
				{ "ua" },
				{ "uai" },
				{ "uan" },
				{ "uang" },
				{ "ue" },
				{ "bui" },
				{ "pui" },
				{ "mui" },
				{ "fui" },
				{ "nui" },
				{ "lui" },
				{ "jui" },
				{ "qui" },
				{ "xui" },
				{ "wui" },
				{ "yui" },
				{ "un" },
				{ "bun" },
				{ "pun" },
				{ "mun" },
				{ "fun" },
				{ "wun" },
				{ "uo" },
				{ "ü" },
				{ "bü" },
				{ "pü" },
				{ "mü" },
				{ "fü" },
				{ "dü" },
				{ "tü" },
				{ "gü" },
				{ "kü" },
				{ "hü" },
				{ "jü" },
				{ "qü" },
				{ "xü" },
				{ "zhü" },
				{ "chü" },
				{ "shü" },
				{ "rü" },
				{ "zü" },
				{ "cü" },
				{ "sü" },
				{ "wü" },
				{ "yü" },
				{ "üe" },
				{ "büe" },
				{ "püe" },
				{ "müe" },
				{ "füe" },
				{ "düe" },
				{ "tüe" },
				{ "güe" },
				{ "küe" },
				{ "hüe" },
				{ "jüe" },
				{ "qüe" },
				{ "xüe" },
				{ "zhüe" },
				{ "chüe" },
				{ "shüe" },
				{ "rüe" },
				{ "züe" },
				{ "cüe" },
				{ "süe" },
				{ "wüe" },
				{ "yüe" },

		});
	}

	@Test(expected = PinyinParseException.class)
	public void test() {
		new PinyinParser().parse(this.text);
	}
}
